backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/img/diario"
public_folder: "/img/diario"

collections:
  - name: "diario"
    label: "Diario"
    folder: "src/pages/diario"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPostLayout.astro"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - label: "Etiqueta"
        name: "tag"
        widget: "select"
        options: ["bitacora", "fotografia", "punto de fuga"]
        default: "bitacora"
      - {label: "Imagen de Portada", name: "main_image", widget: "image", required: false}
      - {label: "Descripción corta", name: "description", widget: "string", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}