backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
locale: "es"

# Configuramos la ruta para que apunte directamente a la carpeta general
media_folder: "public/img/diario"
public_folder: "/img/diario"

collections:
  - name: "diario"
    label: "Diario"
    folder: "src/pages/diario"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPostLayout.astro"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - label: "Etiqueta"
        name: "tag"
        widget: "select"
        options: ["bitacora", "fotografia", "punto de fuga", "vida local", "data", "guia de viaje", "contexto y cultura"]
        default: ""

      - label: "País / Destino"
        name: "pais"
        widget: "select"
        options: 
          - "Nueva Zelanda"
          - "Australia"
          - "Fiji"
          - "Indonesia"
          - "Vietnam"
          - "China"
          - "Tailandia"
          - "Argentina"
          - "Chile"
          - "Múltiple / General"
        default: "General"
        required: false

      - label: "Descripción SEO (Resumen para Google)"
        name: "description"
        widget: "string"
        hint: "Máximo 160 caracteres. Ej: Todo lo que necesitás saber para tramitar tu visa y encontrar alojamiento en tu primer mes."
        required: false

      - {label: "Imagen de Portada", name: "main_image", widget: "image", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}